language: java
jdk:
  - oraclejdk7
before_script:
  - sudo apt-get install subversion
  - svn -h
  - cd fsplatform
script: 
  - mvn test
  - mvn package
after_script:
  - svn checkout https://svn.sinaapp.com/fsplatform/ target --username hopesfish@163.com --password !@#cyrus!@# --no-auth-cache

  - cd target
  - mv fsplatform-0.0.1-SNAPSHOT.war fsplatform.war

  - svn add fsplatform.war

  - svn commit -m "commit war" fsplatform.war
 --username 'hopesfish@163.com' --password '!@#cyrus!@#'