language: java
jdk:
  - oraclejdk7
env:
  global:
    - TIMEOUT=6000000
before_script:
  - sudo apt-get install subversion
  - svn -h
  - cd fsplatform
script: 
  - mvn test
  - mvn package
after_script:
  - svn checkout https://svn.sinaapp.com/fsplatform/1 target --username cloverren@163.com --password cloverren --no-auth-cache
  - cd target
  - mv -f fsplatform-0.0.1-SNAPSHOT.war fsplatform.war
  - svn add fsplatform.war
  - ls -lah
  - svn commit -m "upload war" --username cloverren@163.com --password cloverren --no-auth-cache
  - ping svn.sinaapp.com -i 10000
