language: java
jdk:
  - oraclejdk7
before_script:
  - sudo apt-get install subversion
  - svn -h
  - cd fsplatform
script: 
  - mvn test
  - mvn package
after_script:
  - cd target
  - mv fsplatform-0.0.1-SNAPSHOT.war fsplatform.war

  - svn checkout https://svn.sinaapp.com/fsplatform/ --usernamehopesfish@163.com
  - !@#cyrus!@#
  - svn add fsplatform.war

  - svn commit -m "commit war" fsplatform.war
